# DigitalOcean Playbook
---
- name: DigitalOcean
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:

  - name: Include the variables for droplet creation
    include_vars: group_vars/droplet

  - name: Create Droplet
    digital_ocean:
      state: present
      command: droplet
      name: "{{ droplet_name }}"
      api_token: "{{ digital_ocean_api_token }}"
      size_id: "{{ droplet_size }}"
      region_id: "{{ droplet_region }}"
      image_id: "{{ droplet_image }}"
      ssh_key_ids: "{{ droplet_ssh_key_id }}"
      wait_timeout: 500
    register: droplet_info


  - name: Add new instance to host group
    add_host: hostname={{ droplet_info.droplet.ip_address }} groupname=digital_ocean_droplet

  - name: Wait for SSH to come up
    wait_for: host={{ droplet_info.droplet.ip_address }} port=22 delay=10 timeout=60 state=started

- name: Configure Ubuntu Droplet for user directives
  hosts: digital_ocean_droplet
  remote_user: root
  gather_facts: False

  pre_tasks:

    - name: Install python2 necessary for Ansible
      raw: sudo apt-get -y install python-simplejson

  tasks:

    - name: Create a user with sudo privileges
      user:
        name: dropletuser
        state: present
        shell: /bin/bash
        groups: sudo

    - name: Set authorized key with id_rsa.pub home file
      authorized_key:
        user: dropletuser
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

    - name: Allow run commands as root with dropletuser
      shell: "echo '%sudo ALL=NOPASSWD: ALL' >> /etc/sudoers"


- name: Configure Droplet
  hosts: digital_ocean_droplet
  remote_user: dropletuser
  gather_facts: True

  tasks:

    - name: Install Vim package
      sudo : yes
      apt:
        name: vim
        state: present
        update_cache: yes

    - name: Install htop
      sudo : yes
      apt:
        name: htop
        state: present
        update_cache: yes

    - name: Enable OpenSSH
      sudo: yes
      ufw:
        rule: allow
        name: OpenSSH
